# config.yml

backend:
  name: github
  repo: lkaupp/lkaupp.github.io
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts'
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: title
    fields:
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Tags", name: "tags", widget: "list", allow_add: true, default: [""]}
     - {label: "Style", name: "style", widget: "string"}
     - {label: "Color", name: "color", widget: "string"}
     - {label: "Text", name: "body", widget: "markdown"}
     - {label: "Description", name: "description", widget: "text"}
     - {label: "External URL", name: "external_url", widget: "string", required: false, default: false}
  - name: projects
    label: 'Projects'
    folder: '_projects'
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields:
      - {label: "Title", name: "name", widget: "string"}
      - {label: "Tags", name: "tools", widget: "list", allow_add: true, default: [""]}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "External URL", name: "external_url", widget: "string", required: false, , default: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Text", name: "body", widget: "markdown"}