# config.yml

backend:
  name: github
  repo: lkaupp/lkaupp.github.io
  branch: master # Branch to update (optional; defaults to master)
  auth_type: implicit
  api_root: https://api.github.com
  base_url: https://api.github.com
  auth_endpoint: oauth/authorize
  site_domain: lkaupp.github.io
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }