# config.yml

backend:
  name: github
  repo: lkaupp/lkaupp.github.io
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts'
    fields:
     - {label: "Title", name: "name", widget: "string"}
     - {label: "Tags", name: "tags", widget: "list"}
     - {label: "Style", name: "style", widget: "string"}
     - {label: "Color", name: "color", widget: "string"}
     - {label: "Text", name: "body", widget: "markdown"}
     - {label: "Description", name: "description", widget: "text"}
     - {label: "External URL", name: "external_url", widget: "string"}
  - name: projects
    label: 'Projects'
    folder: '_projects'
    fields:
      - {label: "Title", name: "name", widget: "string"}
      - {label: "Tags", name: "tools", widget: "list"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "External URL", name: "external_url", widget: "string"}